In [1]:
import pandas as pd

In [20]:
employee_data = pd.read_excel('employee_data.xlsx', sheet_name = 'More Employee', na_values = ["—"])
employee_data

             Name   Age Department   Salary            Join_Date
0          Rajesh  29.0        Ops  60000.0          21-05-2023
1           Nasir  31.0    IT Tech  62000.0  2020-12-11 00:00:00
2         Mathiew   NaN    Support  58000.0          15-01-2025
3         Gilbert  29.0        Ops  60000.0          21-05-2021
4           Kevin  28.0    Support  61000.0          30-07-2024
5           Navin  35.0    Support  72000.0          19-08-2023
6             NaN  40.0    IT Tech  64000.0  2022-10-09 00:00:00
7          Roshan  31.0    IT Tech      NaN  2020-12-11 00:00:00
8       Kuppusamy  28.0        Ops      NaN          21-05-2021
9           Ajesh  28.0    Support      NaN          30-07-2024
10           Diya  31.0    IT Tech  63000.0  2020-12-11 00:00:00
11        Mathiew   NaN    Support  58000.0          15-01-2025
12  Jagadheeswari  28.0    IT Tech      NaN                   —
13           Mani  28.0        Ops      NaN          21-05-2021

In [22]:
employee_data.isna().sum()

Name          1
Age           2
Department    0
Salary        5
Join_Date     0
dtype: int64

In [28]:
employee_data.drop_duplicates(inplace= True)

In [31]:
employee_data[employee_data['Department'] == 'Support']

      Name   Age Department   Salary    Join_Date
2  Mathiew   NaN    Support  58000.0  15-01-2025
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
9    Ajesh  28.0    Support      NaN  30-07-2024

In [36]:
mask = employee_data['Salary'].isna()
mask

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7      True
8      True
9      True
10    False
12     True
13     True
Name: Salary, dtype: bool

In [42]:
employee_data['Salary'] = employee_data['Salary'].fillna(employee_data.groupby('Department')['Salary'].transform('mean'))

In [52]:
employee_data['Age'] = employee_data['Age'].fillna(employee_data.groupby('Department')['Age'].mean())

In [53]:
employee_data[employee_data['Department'] == 'Support']

      Name        Age Department        Salary    Join_Date
2  Mathiew  30.333333    Support  58000.000000  15-01-2025
4    Kevin  28.000000    Support  61000.000000  30-07-2024
5    Navin  35.000000    Support  72000.000000  19-08-2023
9    Ajesh  28.000000    Support  63666.666667  30-07-2024

TASK  
1. Impute relevant values in salary column wherever it is NAN, based on Department Filtering  
2. Impute mathews age at 27